# Generated by Django 5.1.6 on 2025-02-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
